var book1 = require('./book.js')()
var book2 = require('./book.js')()
book1.setName("A")
book2.setName("B")
console.log("Let's read: " + book1.getName())
console.log("Let's read: " + book2.getName())
